package org.strangeway.msa.db

val SHARE_JAVA_PACKAGE_PREFIXES = listOf(
  "com.google.common.",
  "com.haulmont.cuba.",
  "com.intellij.util.",
  "io.grpc.",
  "io.javalin.",
  "io.jmix.",
  "io.ktor.",
  "io.micronaut.",
  "io.netty.",
  "io.quarkus.",
  "io.reactivex.",
  "io.restassured",
  "io.rsocket.",
  "io.smallrye.",
  "io.vertx.",
  "jakarta.",
  "java.",
  "javax.",
  "jdbi.",
  "kong.unirest.",
  "kotlinx.",
  "okhttp3.",
  "org.apache.",
  "org.eclipse.",
  "org.hibernate.",
  "org.http4k.",
  "org.jooby.",
  "org.jooq.",
  "org.springframework.",
  "retrofit2."
)